source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0' # or platform :osx, '10.10' if your target is OS X.
use_frameworks!

target 'swinject-demo' do
	pod 'Swinject', '~> 2.1.0'
end
# Uncomment if you use SwinjectStoryboard
# pod 'SwinjectStoryboard', '~> 1.0.0'